name: Build PC2L

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get -y install libopenmpi-dev libgtest-dev libbenchmark-dev && pip install clang-format

    - name: Check formatting
      # Check that all of the source code is properly formatted with clang-format
      # uses the .clang-format file from the root of the repo
      run: cd ${{github.workspace}} && find . -iname '*.h' -o -iname '*.cpp' | xargs clang-format --style=LLVM -i --dry-run -Werror

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build 

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose

